site_name: VIM Universal
site_url: https://shawnvim.github.io/vim-universal
repo_name: shawnvim/vim-universal
repo_url: https://github.com/shawnvim/vim-universal
edit_uri: ''
theme:
  name: 'mkdocs'
  palette:
    primary: 'red'
    accent: 'red'
nav:
  - Overview: index.md
markdown_extensions:
  - admonition
