remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

title:  VIM-Universal
description: A Universal VIM Integration
favicon: true
color-scheme: auto


# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/shawnvim/vim-universal

navigation:
  - name: Intro
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#todo
  - name: VIM Universal Newbie Guide.md
    link: ./newbie-guide.html


