remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

title:  VIM Universal
description: A Universal VIM Integration
favicon: true
color-scheme: auto


# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/shawnvim/

navigation:
  - name: Intro
    link: ./index.html
  - name: VIM Cheat Sheet
    link: ./cheat-sheet.html
  - name: VIM Universal Newbie Guide
    link: ./newbie-guide.html
  - name: VIM LSP
    link: ./lsp.html
    sublist:
      - name: Installation
        link: ./lsp.html#installation
      - name: Reference
        link: ./lsp.html#reference
  - name: VIM RTP
    link: ./rtp.html


