remote_theme: BDHU/minimalist

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

email: qiushihao@outlook.com
description: VIM-Universal
favicon: true
color-scheme: auto


# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitHub
    link: https://github.com/
  - name: Twitter
    link: https://twitter.com/
  - name: Project Repository
    link: https://github.com/shawnvim/vim-universal

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
