name: Build
on:
  push:
    branches-ignore:
      - 'mkdocs'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: mkdocs build -s
