name: build

on:
  push:
    branches:
      - master
jobs:
  embed_code:
    name: Embed Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - run: npm install -g embedme
      - run: embedme README.md
      - uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
